#version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./plugins/rabbitmq_delayed_message_exchange-3.12.0.ez:/plugins/rabbitmq_delayed_message_exchange-3.12.0.ez
    command:
      - /bin/bash
      - -c
      - |
        # 启用插件
        rabbitmq-plugins enable rabbitmq_delayed_message_exchange
        
        # 启动RabbitMQ
        rabbitmq-server
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 60s

  redis:
    image: redis:7.0.12
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: root
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/data:/data
    command:
      - /bin/sh
      - -c
      - "exec redis-server --requirepass \"$$REDIS_PASSWORD\""
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 60s

  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos_config
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos
      TZ: Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-proot" ]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 60s

  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: nacos
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MODE: standalone
      # 数据库配置
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
      MYSQL_SERVICE_DB_PARAM: "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Shanghai"
      # 安全配置
      #- NACOS_AUTH_ENABLE=true
      #- NACOS_AUTH_TOKEN=Your_Strong_Token_32bytes_Length_1234567890
      #- NACOS_AUTH_IDENTITY_KEY=ServerIdentityKey
      #- NACOS_AUTH_IDENTITY_VALUE=Your_Unique_Identity_Value
      JVM_XMS: 256m
      JVM_XMX: 500m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./data/nacos/data:/home/nacos/data
      - ./data/nacos/logs:/home/nacos/logs
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos/actuator/health" ]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 90s

networks:
  app-network:
    driver: bridge
